import { Inter } from 'next/font/google'
import { signIn, signOut, useSession } from 'next-auth/react'

// import Head from 'next/head'
// import Image from 'next/image'
// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { data: session } = useSession()
  if (session) {
    return (
      <>
        Signed in as {session.user?.email} <br/>
        <button onClick={() => signOut()}>Sign out</button>
      </>
    )
  }
  return (
    <>
      Not signed in <br />
      <button onClick={() => signIn()}>Sign in</button>
    </>
  )
  // return (
  //   <div>
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>
  //     <main>
  //       <div className="p-10 font-bold text-red-500">Hello Tailwind CSS!</div>
  //     </main>
  //   </div>
  // )
}
